[build]
  publish = "."
  ignore = "exit 0"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "geolocation=(self)"
